//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaProMAX01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Empleado = new HashSet<Empleado>();
            this.USUARIO_LOGIN = new HashSet<USUARIO_LOGIN>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int idPersona { get; set; }
        public int Codigo { get; set; }

        public string Cedula { get; set; }
        
        public string nombre { get; set; }
        [StringLength(20, ErrorMessage = "El titulo no debe ser mayor a 10 caracteres")]
        public string Primer_Apellido { get; set; }
        public string Segund_Apellido { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        [RegularExpression("^[0-9]*$", ErrorMessage = "Solo se permiten números")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El número es obligatorio")]
        [StringLength(12, ErrorMessage = "El número es demasiado largo")]
        public string Telefono { get; set; }
        [StringLength(8, ErrorMessage = "El titulo no debe ser mayor a 10 caracteres")]
        public string Correo { get; set; }
        public string Sexo { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_LOGIN> USUARIO_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
